/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated.guests'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated.gallery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminDiscountCodesIndexRouteImport } from './routes/admin.discount-codes.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AuthenticatedMosaicIndexRouteImport } from './routes/_authenticated.mosaic.index'
import { Route as ESlugTimelineRouteImport } from './routes/e.$slug.timeline'
import { Route as ESlugGuestbookRouteImport } from './routes/e.$slug.guestbook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/admin.payments.$paymentId'
import { Route as AdminDiscountCodesIdRouteImport } from './routes/admin.discount-codes.$id'
import { Route as AdminCustomersUserIdRouteImport } from './routes/admin.customers.$userId'
import { Route as AuthenticatedMosaicEventIdRouteImport } from './routes/_authenticated.mosaic.$eventId'
import { Route as AuthenticatedEditEventEventIdRouteImport } from './routes/_authenticated.edit-event.$eventId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountCodesIndexRoute = AdminDiscountCodesIndexRouteImport.update({
  id: '/discount-codes/',
  path: '/discount-codes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedMosaicIndexRoute =
  AuthenticatedMosaicIndexRouteImport.update({
    id: '/mosaic/',
    path: '/mosaic/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ESlugTimelineRoute = ESlugTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugGuestbookRoute = ESlugGuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => ESlugRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountCodesIdRoute = AdminDiscountCodesIdRouteImport.update({
  id: '/discount-codes/$id',
  path: '/discount-codes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersUserIdRoute = AdminCustomersUserIdRouteImport.update({
  id: '/customers/$userId',
  path: '/customers/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedMosaicEventIdRoute =
  AuthenticatedMosaicEventIdRouteImport.update({
    id: '/mosaic/$eventId',
    path: '/mosaic/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditEventEventIdRoute =
  AuthenticatedEditEventEventIdRouteImport.update({
    id: '/edit-event/$eventId',
    path: '/edit-event/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/edit-event/$eventId': typeof AuthenticatedEditEventEventIdRoute
  '/mosaic/$eventId': typeof AuthenticatedMosaicEventIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/discount-codes/$id': typeof AdminDiscountCodesIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/e/$slug/guestbook': typeof ESlugGuestbookRoute
  '/e/$slug/timeline': typeof ESlugTimelineRoute
  '/mosaic/': typeof AuthenticatedMosaicIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discount-codes/': typeof AdminDiscountCodesIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/edit-event/$eventId': typeof AuthenticatedEditEventEventIdRoute
  '/mosaic/$eventId': typeof AuthenticatedMosaicEventIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/discount-codes/$id': typeof AdminDiscountCodesIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/e/$slug/guestbook': typeof ESlugGuestbookRoute
  '/e/$slug/timeline': typeof ESlugTimelineRoute
  '/mosaic': typeof AuthenticatedMosaicIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discount-codes': typeof AdminDiscountCodesIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/edit-event/$eventId': typeof AuthenticatedEditEventEventIdRoute
  '/_authenticated/mosaic/$eventId': typeof AuthenticatedMosaicEventIdRoute
  '/admin/customers/$userId': typeof AdminCustomersUserIdRoute
  '/admin/discount-codes/$id': typeof AdminDiscountCodesIdRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/e/$slug/guestbook': typeof ESlugGuestbookRoute
  '/e/$slug/timeline': typeof ESlugTimelineRoute
  '/_authenticated/mosaic/': typeof AuthenticatedMosaicIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discount-codes/': typeof AdminDiscountCodesIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/gallery'
    | '/guests'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/auth/callback'
    | '/e/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/edit-event/$eventId'
    | '/mosaic/$eventId'
    | '/admin/customers/$userId'
    | '/admin/discount-codes/$id'
    | '/admin/payments/$paymentId'
    | '/api/public/stripe-webhook'
    | '/e/$slug/guestbook'
    | '/e/$slug/timeline'
    | '/mosaic/'
    | '/admin/customers/'
    | '/admin/discount-codes/'
    | '/admin/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/gallery'
    | '/guests'
    | '/onboarding'
    | '/settings'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/auth/callback'
    | '/e/$slug'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/edit-event/$eventId'
    | '/mosaic/$eventId'
    | '/admin/customers/$userId'
    | '/admin/discount-codes/$id'
    | '/admin/payments/$paymentId'
    | '/api/public/stripe-webhook'
    | '/e/$slug/guestbook'
    | '/e/$slug/timeline'
    | '/mosaic'
    | '/admin/customers'
    | '/admin/discount-codes'
    | '/admin/payments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/gallery'
    | '/_authenticated/guests'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/settings'
    | '/admin/system-health'
    | '/auth/callback'
    | '/e/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/edit-event/$eventId'
    | '/_authenticated/mosaic/$eventId'
    | '/admin/customers/$userId'
    | '/admin/discount-codes/$id'
    | '/admin/payments/$paymentId'
    | '/api/public/stripe-webhook'
    | '/e/$slug/guestbook'
    | '/e/$slug/timeline'
    | '/_authenticated/mosaic/'
    | '/admin/customers/'
    | '/admin/discount-codes/'
    | '/admin/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discount-codes/': {
      id: '/admin/discount-codes/'
      path: '/discount-codes'
      fullPath: '/admin/discount-codes/'
      preLoaderRoute: typeof AdminDiscountCodesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/mosaic/': {
      id: '/_authenticated/mosaic/'
      path: '/mosaic'
      fullPath: '/mosaic/'
      preLoaderRoute: typeof AuthenticatedMosaicIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/e/$slug/timeline': {
      id: '/e/$slug/timeline'
      path: '/timeline'
      fullPath: '/e/$slug/timeline'
      preLoaderRoute: typeof ESlugTimelineRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/guestbook': {
      id: '/e/$slug/guestbook'
      path: '/guestbook'
      fullPath: '/e/$slug/guestbook'
      preLoaderRoute: typeof ESlugGuestbookRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/$paymentId': {
      id: '/admin/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discount-codes/$id': {
      id: '/admin/discount-codes/$id'
      path: '/discount-codes/$id'
      fullPath: '/admin/discount-codes/$id'
      preLoaderRoute: typeof AdminDiscountCodesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$userId': {
      id: '/admin/customers/$userId'
      path: '/customers/$userId'
      fullPath: '/admin/customers/$userId'
      preLoaderRoute: typeof AdminCustomersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/mosaic/$eventId': {
      id: '/_authenticated/mosaic/$eventId'
      path: '/mosaic/$eventId'
      fullPath: '/mosaic/$eventId'
      preLoaderRoute: typeof AuthenticatedMosaicEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit-event/$eventId': {
      id: '/_authenticated/edit-event/$eventId'
      path: '/edit-event/$eventId'
      fullPath: '/edit-event/$eventId'
      preLoaderRoute: typeof AuthenticatedEditEventEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEditEventEventIdRoute: typeof AuthenticatedEditEventEventIdRoute
  AuthenticatedMosaicEventIdRoute: typeof AuthenticatedMosaicEventIdRoute
  AuthenticatedMosaicIndexRoute: typeof AuthenticatedMosaicIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEditEventEventIdRoute: AuthenticatedEditEventEventIdRoute,
  AuthenticatedMosaicEventIdRoute: AuthenticatedMosaicEventIdRoute,
  AuthenticatedMosaicIndexRoute: AuthenticatedMosaicIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersUserIdRoute: typeof AdminCustomersUserIdRoute
  AdminDiscountCodesIdRoute: typeof AdminDiscountCodesIdRoute
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountCodesIndexRoute: typeof AdminDiscountCodesIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersUserIdRoute: AdminCustomersUserIdRoute,
  AdminDiscountCodesIdRoute: AdminDiscountCodesIdRoute,
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountCodesIndexRoute: AdminDiscountCodesIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ESlugRouteChildren {
  ESlugGuestbookRoute: typeof ESlugGuestbookRoute
  ESlugTimelineRoute: typeof ESlugTimelineRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugGuestbookRoute: ESlugGuestbookRoute,
  ESlugTimelineRoute: ESlugTimelineRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ESlugRoute: ESlugRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
